# Application Name
spring.application.name=kalanden

# Supabase API Configuration
supabase.url=https://aqfwsgieequeqdcwneff.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZndzZ2llZXF1ZXFkY3duZWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1OTc0NzksImV4cCI6MjA1ODE3MzQ3OX0.OS5figsWYDiAe5zoutSSPY8HlvGiNeId6i_9RMBibM8

# Hibernate (Not used directly, but kept for potential local DB use)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configuration (Replace with your broker address)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group_kalanden
spring.kafka.producer.retries=3
spring.kafka.producer.acks=all

## Security Configuration
#spring.security.user.name=admin
#spring.security.user.password=admin123
